using Npgsql;
using SimpleDBDiff.Core;
using SimpleDBDiff.Postgres;

namespace SimpleDBDiff.Tests;

public sealed class PostgresIntegrationTests
{
    private static readonly PostgresSchemaReader Reader = new();
    private static readonly PostgresMigrationGenerator Generator = new();
    private static string? LeftConnection => Environment.GetEnvironmentVariable("SIMPLEDBDIFF_TEST_LEFT");
    private static string? RightConnection => Environment.GetEnvironmentVariable("SIMPLEDBDIFF_TEST_RIGHT");

    [Fact]
    public async Task LoadsDifferentSchemasAndGeneratedSqlMakesTargetMatchSource()
    {
        if (LeftConnection is null || RightConnection is null) return;
        await ResetAsync(LeftConnection, """
            CREATE SCHEMA sdd_it;
            CREATE TABLE sdd_it.categories (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, label text NOT NULL UNIQUE);
            CREATE TABLE sdd_it.orders (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY, category_id integer, note text NOT NULL DEFAULT 'new' CHECK (length(note) > 0), source_only boolean);
            ALTER TABLE sdd_it.orders ADD CONSTRAINT orders_category_fk FOREIGN KEY (category_id) REFERENCES sdd_it.categories(id);
            CREATE INDEX orders_note_idx ON sdd_it.orders(note);
            """);
        await ResetAsync(RightConnection, """
            CREATE SCHEMA sdd_it;
            CREATE TABLE sdd_it.orders (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, note varchar(20) DEFAULT 'old', target_only text);
            CREATE INDEX orders_target_idx ON sdd_it.orders(target_only);
            CREATE TABLE sdd_it.legacy (id integer PRIMARY KEY);
            """);

        var left = await FixtureAsync(LeftConnection);
        var right = await FixtureAsync(RightConnection);
        var diff = SchemaComparer.Compare(left, right);
        Assert.Contains(diff, d => d.Kind == DifferenceKind.Different && d.ObjectName == "note");
        Assert.Contains(diff, d => d.Kind == DifferenceKind.LeftOnly && d.ObjectName == "sdd_it.categories");
        Assert.Contains(diff, d => d.Kind == DifferenceKind.RightOnly && d.ObjectName == "sdd_it.legacy");
        Assert.Contains(diff, d => d.Kind == DifferenceKind.LeftOnly && d.ObjectName == "orders_category_fk");
        Assert.Contains(diff, d => d.Kind == DifferenceKind.LeftOnly && d.ObjectName == "orders_note_idx");

        var script = Generator.Generate(left, right);
        Assert.Contains("DROP TABLE \"sdd_it\".\"legacy\"", script);
        await ExecuteAsync(RightConnection, script);
        var after = await FixtureAsync(RightConnection);
        Assert.All(SchemaComparer.Compare(left, after), d => Assert.Equal(DifferenceKind.Equal, d.Kind));
        Assert.Contains("DROP TABLE \"sdd_it\".\"categories\"", Generator.Generate(after with { Tables = [] }, after));
    }

    [Fact]
    public async Task InvalidDatabaseConnectionIsReported()
    {
        if (LeftConnection is null) return;
        var invalid = new NpgsqlConnectionStringBuilder(LeftConnection) { Database = "sdd_database_does_not_exist", Timeout = 2 };
        await Assert.ThrowsAsync<PostgresException>(() => Reader.LoadAsync(invalid.ConnectionString));
    }

    [Fact]
    public async Task UnsupportedPartitionMetadataFailsClearly()
    {
        if (LeftConnection is null) return;
        await ExecuteAsync(LeftConnection, "CREATE SCHEMA IF NOT EXISTS sdd_it; CREATE TABLE sdd_it.partition_probe (id integer) PARTITION BY RANGE (id)");
        try
        {
            var error = await Assert.ThrowsAsync<NotSupportedException>(() => Reader.LoadAsync(LeftConnection));
            Assert.Contains("partition_probe", error.Message);
        }
        finally { await ExecuteAsync(LeftConnection, "DROP TABLE sdd_it.partition_probe"); }
    }

    private static async Task<SchemaSnapshot> FixtureAsync(string connection)
    {
        var all = await Reader.LoadAsync(connection);
        return new(all.Tables.Where(t => t.Schema == "sdd_it").ToArray());
    }

    private static async Task ResetAsync(string connection, string sql)
    {
        await ExecuteAsync(connection, "DROP SCHEMA IF EXISTS sdd_it CASCADE; " + sql);
    }

    private static async Task ExecuteAsync(string connection, string sql)
    {
        await using var dataSource = NpgsqlDataSource.Create(connection);
        await using var command = dataSource.CreateCommand(sql);
        await command.ExecuteNonQueryAsync();
    }
}
