DROP SCHEMA IF EXISTS demo CASCADE;
CREATE SCHEMA demo;
CREATE TABLE demo.customers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(120) NOT NULL,
    legacy_code text
);
CREATE TABLE demo.orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer,
    description varchar(80) DEFAULT 'old',
    amount numeric(10,2)
);
CREATE INDEX orders_description_idx ON demo.orders(description);
CREATE TABLE demo.retired (id integer PRIMARY KEY);
