DROP SCHEMA IF EXISTS demo CASCADE;
CREATE SCHEMA demo;
CREATE TABLE demo.customers (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    active boolean NOT NULL DEFAULT true
);
CREATE TABLE demo.orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES demo.customers(id),
    description text DEFAULT 'new',
    amount numeric(12,2) NOT NULL CHECK (amount >= 0)
);
CREATE INDEX orders_amount_idx ON demo.orders(amount);
